### PR TITLE
Preparing release for v2.0.7

### PR DESCRIPTION
**Pull request by madsem**
preparing a new release. Optimizer now uses a CLI command field only, everything is now referenced via placeholders. Some bugfixes & code improvements.

### CODE REVIEW

**Comment by 4rn0** [comment]
> This new version uses placeholders by default for all optimizers, that makes it easier to maintain instead of keeping two ways of building commands (one for default optimizers without dynamic placeholders, and one with).

I understand why you did this, but I think I prefer the simpler UI with advanced option. You are obviously a power user and want to see and tweak those settings. You are familiar with them, but I think they will intimidate the less advanced users that are looking for a simple plug and play solution.

> Also improved the binary finder slightly, you were passing in a full path, which made the binary finder return false when using custom libraries. It also throws an error now when binary isn't installed on system and logs it. [...] For binaries, you only need to pass the name in now, path will be automatically found with the binaryfinder method, also for custom optimizers.

I like some of the changes you made, but not the {binary:name) stuff. Some reason as above: I think it's easier to just pass in paths for the advanced optimizers. BTW The binary finder wasn't used with advanced settings. :-)

> Improved the way temp files are moved, and added a check for filesize. Since then I have made many tests but never again had zero byte files.

Very nice! I'll clean up the code a bit (you're calling filesize on the tempfile twice?), but I definitely want to have this in the addon!

> Added a workaround for the glide.generated event, just committed it [...] And there is another issue I just figured out, the glide.generated event, is also fired on every page load when images are served direct from cache...

That is awesome! I'd like to refactor it a bit and move it from the listener to the ImageOptimizer class, but I love what you did here!

---

I'm very happy with what you did! I think I'll just merge your PR and then make some of the changes and cleanup and we're good to tag a new release!

**Comment by madsem** [comment]
cool sounds good!

Regarding the UI, nothing changed there. I mean i switched everything in the code to dynamic insertion. Simple settings work exactly like before.

The binary finder was actually fired and returned false with cjpeg :) But have a look at it.

Install it and have a look over it! ;)

**Comment by 4rn0** [comment]
> The binary finder was actually fired and returned false with cjpeg :) But have a look at it.

I did! 😉
https://github.com/4rn0/statamic-image-optimizer/blob/master/ImageOptimizer/ImageOptimizer.php#L123

**Comment by 4rn0** [comment]
@madsem The 2.0.7 branch now contains your work and the changes I made after that.  If you'd like you can have a look before I merge it back into master and release it.

https://github.com/4rn0/statamic-image-optimizer/tree/v2.0.7

**Comment by madsem** [comment]
> > The binary finder was actually fired and returned false with cjpeg :) But have a look at it.
> 
> I did! 😉
> https://github.com/4rn0/statamic-image-optimizer/blob/master/ImageOptimizer/ImageOptimizer.php#L123

yeah, you know what. I probably already changed that line and that's why it fired :)



> @madsem The 2.0.7 branch now contains your work and the changes I made after that. If you'd like you can have a look before I merge it back into master and release it.
> 
> https://github.com/4rn0/statamic-image-optimizer/tree/v2.0.7

awesome, will install in a bit and give it a whirl 👍

**Pull request merged**
